# Generated by Django 6.0.2 on 2026-03-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0002_category_subscribers_categorysubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategorySubscriber',
        ),
    ]
