# Generated by Django 6.0.3 on 2026-03-16 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstr_api', '0002_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: +7 (xxx) xxx-xx-xx', regex='^\\+7 \\(\\d{3}\\) \\d{3}-\\d\\d-\\d\\d$')]),
        ),
    ]
