# Generated by Django 6.0.3 on 2026-03-17 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstr_api', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: +7 (xxx) xxx-xx-xx', regex='^\\+7 \\(\\d{3}\\) \\d{3}-\\d\\d-\\d\\d$')]),
        ),
    ]
