# Generated by Django 6.0.3 on 2026-03-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstr_api', '0005_alter_coords_latitude_alter_coords_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('pending', 'На проверке'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='new', max_length=20),
        ),
    ]
